# Site settings
title: Heather Storm
email: missheatherlaree@gmail.com
description: Create. Innovate.
baseurl: "" 
url: "" 
github_username: slychika

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
